top/staff/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('order/<int:pk>', views.order, name='order'),
    path('order_edit/<int:pk>', views.order_edit, name='order_edit'),
    path('product_create/', views.product_create, name='product_create'),
    path('cancel_requests/', views.cancel_requests, name='cancel_requests')
]

top/top/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include(('store.urls', 'store'), namespace='store')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('staff/', include(('staff.urls', 'staff'), namespace='staff')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

top/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password'),
]

top/staff/models.py
from django.db import models

class CancelRequest(models.Model):
    order = models.ForeignKey('store.Order', on_delete=models.CASCADE)

top/staff/forms.py
from django import forms
from .bulma_mixin import BulmaMixin
from store.models import Order, STATUS, Product, Category, Brand


class OrderEditForm(BulmaMixin, forms.ModelForm):
    address = forms.CharField(label="Изменить адрес")
    status = forms.ChoiceField(label="Изменить статус", choices=STATUS)

    class Meta:
        model = Order
        fields = ['address', 'status']


class ProductForm(BulmaMixin, forms.ModelForm):
    name = forms.CharField(label='Имя продукта', widget=forms.TextInput(attrs={'class': 'input'}))
    slug = forms.CharField(label='Slug', widget=forms.TextInput(attrs={'class': 'input'}))
    description = forms.CharField(label='Описание', widget=forms.TextInput(attrs={'class': 'input'}))
    price = forms.IntegerField(label='Цена', widget=forms.NumberInput(attrs={'class': 'input'}))
    is_new = forms.CharField(widget=forms.CheckboxInput(), label='Новый продукт', required=False)
    is_discounted = forms.CharField(widget=forms.CheckboxInput(), label='Скидка', required=False)
    category = forms.ModelChoiceField(queryset=Category.objects.all())
    brand = forms.ModelChoiceField(queryset=Brand.objects.all())
    image = forms.ImageField()

    class Meta:
        model = Product
        fields = [
            'name',
            'slug',
            'description',
            'price',
            'is_new',
            'is_discounted',
            'category',
            'brand',
            'image',
        ]

top/staff/views.py
from django.contrib.sites import requests
from django.shortcuts import render, redirect
from store.models import Order, STATUS
from .forms import OrderEditForm, ProductForm
from .models import CancelRequest
from django.db.models import Q


def home(request):
    orders = Order.objects.all()
    status = request.GET.get('status')
    orders = orders.filter(status=status) if status else orders

    search = request.GET.get('search')
    orders = orders.filter(
        Q(pk__icontains=search) |
        Q(customer__username__icontains=search)) \
        if search else orders

    return render(request, 'admin.html', {'orders': orders, 'status': STATUS})


def order(request, pk):
    order_data = Order.objects.get(pk=pk)
    return render(request, 'order.html', {'order': order_data})


def order_edit(request, pk):
    order_data = Order.objects.get(pk=pk)
    form = OrderEditForm(request.POST or None, instance=order_data)
    allowed_status = ['Создан', 'Принят', 'В сборке']

    if not request.POST.get('address'):
        form.address = order_data.address

    if form.is_valid():
        form.save()
        return redirect('staff:order', pk=pk)
    return render(request, 'order_edit.html', {'form': form, 'order': order_data, 'allowed_status': allowed_status})


def product_create(request):
    form = ProductForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('store:home')
    return render(request, 'product_create.html', {'form': form})


def cancel_requests(request):
    requests = CancelRequest.objects.all()
    action = request.GET.get('action')
    pk = request.GET.get('pk')

    if action:
        if action == 'confirm':
            CancelRequest.objects.get(pk=pk).order.delete()
        elif action == 'cancel':
            CancelRequest.objects.get(pk=pk).delete()
        return redirect('staff:cancel_requests')
    return render(request, 'cancel_requests.html', {'requests': requests})

top/staff/templates/admin.html
{% extends 'admin_layout.html' %}
{% block content %}
    <div class="container">
        <div class="tabs is-centered">
            <ul>
                <li>
                    <a href="{% url 'staff:home' %}">
                        <div class="title is-5 is-success">Все заказы</div>
                    </a>
                </li>
                {% for i in status %}
                    <li class="is-active">
                        <a href="{% url 'staff:home' %}?status={{ i.0 }}">
                            <div class="title is-5">
                                {{ i.0 }}
                            </div>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="columns is-centered">
            <div class="column is-6">
                <form>
                    <div class="field has-addons">
                        <div class="control" style="width: 100%">
                            <input type="text" class="input" name="search" placeholder="Поиск заказов">
                        </div>
                        <div class="control">
                            <button class="button is-success">
                                <ion-icon name="search-outline"></ion-icon>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <section class="section">
            <div class="container has-text-centered">
                <div class="title">Заказы</div>
                <div class="columns is-multiline is-centered">
                    {% for order in orders %}
                        <div class="column is-3 is-centered">
                            <div class="box">
                                <div class="title is-5 has-text-centered">
                                    Заказ №{{ order.pk }}
                                    <span class="tag is-medium is-success">
                                    {{ order.status }}
                                </span>
                                </div>
                                <div class="subtitle">
                                    Покупатель:
                                    <span class="is-italic has-text-weight-bold">
                                {{ order.customer }}
                            </span>
                                </div>
                                <a href="{% url 'staff:order' order.pk %}" class="button is-fullwidth">
                                    Перейти
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
    </div>
    </section>
{% endblock %}

top/staff/templates/admin_layout.html
{% load static from static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'static/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'static/style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</head>
<body>
<nav class="navbar">
    <div class="navbar-brand">
        <a href="{% url 'staff:home' %}" class="navbar-item">
            <ion-icon name="person-outline"></ion-icon>
        </a>
    </div>
    <div class="navbar-menu">
        <div class="navbar-start">
            <a href="{% url 'store:home' %}" class="navbar-item">
                Страница магазина
            </a>
            <a href="{% url 'staff:product_create' %}" class="navbar-item">
                Создать товар
            </a>
        </div>
        <div class="navbar-end">
            <a href="{% url 'staff:cancel_requests' %}" class="navbar-item">
                Запросы на отмену
            </a>
            <a href="{% url 'users:sign_out' %}" class="navbar-item">
                Выйти
            </a>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

top/staff/templates/cancel_requests.html
{% extends 'admin_layout.html' %}

{% block content %}
    <div class="section">
        <div class="container">
            {% if requests %}
                <div class="box">
                    <table class="table is-bordered is-striped is-hoverable is-fullwidth">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>Номер заказа</th>
                            <th>Состав</th>
                            <th>Общая сумма</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for cancel_request in requests %}
                            <tr>
                                <td>{{ cancel_request.pk }}</td>
                                <td>{{ cancel_request.order.pk }}</td>
                                <td>{{ cancel_request.order.order_products_list }}</td>
                                <td>{{ cancel_request.order.total_price }} рублей</td>
                                <td>
                                    <a class="button is-success is-small"
                                       href="{% url 'staff:cancel_requests' %}?action=confirm&pk={{ cancel_request.pk }}">
                                        <ion-icon name="checkmark"></ion-icon>
                                    </a>
                                    <a class="button is-danger is-small"
                                       href="{% url 'staff:cancel_requests' %}?action=cancel&pk={{ cancel_request.pk }}">
                                        <ion-icon name="close"></ion-icon>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="title has-text-centered">
                    Пока нет запросов
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

top/staff/templates/order.html
{% extends 'admin_layout.html' %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="title has-text-centered">
                Заказ №{{ order.pk }}
            </div>
            <div class="columns is-centered is-vcentered">
                <div class="column is-7">
                    <div class="box">
                        <table class="table is-fullwidth">
                            <thead>
                            <tr>
                                <th>Имя товара</th>
                                <th>Кол-во</th>
                                <th>Общая сумма</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for product in order.order_products.all %}
                                <tr>
                                    <td>{{ product }}</td>
                                    <td>{{ product.amount }} шт.</td>
                                    <td>{{ product.total }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="3" class="has-text-right has-text-weight-bold">
                                    Общая сумма: {{ order.total_price }} dollars
                                </td>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <div class="column">
                    <div class="box">
                        <div class="title is-3">
                            Информация о покупателе
                        </div>
                        <div class="title is-4">
                            <ion-icon name="person" class="mr-4"></ion-icon>
                            {{ order.customer.username }}
                        </div>
                        <div class="title is-4">
                            <ion-icon name="home" class="mr-4"></ion-icon>
                            {{ order.address }}
                        </div>
                        <div class="title is-4">
                            <ion-icon name="call" class="mr-4"></ion-icon>
                            {{ order.phone }}
                        </div>
                        <div class="title is-4">
                            <ion-icon name="information-circle"></ion-icon>
                            {% if order.status %}
                                {{ order.status }}
                            {% else %}
                                Статус не выбран
                            {% endif %}
                        </div>
                        <div class="title is-6 has-text-grey">
                            <ion-icon name="chatbox-outline"></ion-icon>
                            {% if order.comment %}
                                {{ order.comment }}
                            {% else %}
                                Пусто
                            {% endif %}
                        </div>
                            <a href="{% url 'staff:order_edit' order.pk %}" class="button is-fullwidth">
                                Отредактировать заказ
                            </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

top/staff/templates/order_edit.html
{% extends 'admin_layout.html' %}

{% block content %}
    <section class="section">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-5">
                    <div class="box">
                        <form action="" method="post">
                            {% csrf_token %}
                            {% for field in form %}

                                {% if field.name == 'status' %}
                                    <div class="select is-fullwidth">
                                        {{ field }}
                                    </div>
                                {% else %}

                                    <div class="field">
                                        <label for="{{ field.id_for_label }}" class="label">
                                            {{ field.label }}
                                        </label>
                                        <div class="control">
                                            {% if order.status not in allowed_status %}
                                                <input type="text" name="address" value="{{ field.value }}" readonly
                                                       class="input" required id="id_address">
                                            {% else %}
                                                {{ field }}
                                            {% endif %}
                                        </div>
                                    </div>
                                {% endif %}

                            {% endfor %}
                            <button class="button is-success my-4">
                                Okay
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

top/staff/templates/product_create.html
{% extends 'admin_layout.html' %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-6">
                    <form action="" method="post" class="product-form" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.name == 'is_new' or field.name == 'is_discounted' %}
                                <label for="{{ field.id_for_label }}" class="checkbox">
                                    {{ field }}
                                    {{ field.label }}
                                </label>
                                <br><br>
                            {% elif field.name == 'category' or field.name == 'brand' %}
                                <label for="{{ field.id_for_label }}" class="label">
                                    {{ field.label }}
                                </label>
                                <div class="select is-fullwidth">{{ field }}</div>
                            {% else %}
                                <div class="field">
                                    <label for="{{ field.id_for_label }}" class="label">
                                        {{ field.label }}
                                    </label>
                                    <div class="control">{{ field }}</div>
                                </div>
                            {% endif %}

                        {% endfor %}
                        {% if form.errors %}
                            <ul>
                                {% for error in form.errors.values %}
                                    <li class="has-text-danger">{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <button class="button is-success">Добавить товар</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}